/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example;

import org.example.ExcelReader.MissionExcelReader;
import org.example.editors.ChangeScreenSize;
import org.example.editors.ImagePanel;
import org.example.editors.TextEditorGameWorld;

import javax.swing.*;
import java.io.IOException;


/**
 *
 * @author kzsbv
 */
public class Program extends javax.swing.JFrame {

    private GameWorld gameWorld = new GameWorld();
    private TextEditorGameWorld textEditorGameWorld;

    public Program() {
        try {
            initComponents();
            MissionExcelReader.readData();
        } catch (IOException e) {
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
        ChangeScreenSize.setLocation(this);

    }

    private void initGameWorld() {
        textEditorGameWorld = new TextEditorGameWorld(jLabelCurrentRegion,jTableCurrentRegion, jPanelGameImage);
        textEditorGameWorld.createTextEditorMap(jListMap);
        textEditorGameWorld.createTextEditorBag(jListItems);
        textEditorGameWorld.createTextEditorMission(jTextAreaDesription, jLabelTask, jLabelTaskProgress,jLabelMissionComplete, gameWorld.getPlayer(),jButtonFinishGame);
        textEditorGameWorld.createTextEditorStory(jTextAreaBeginStory,jTextAreaEndStory);
        textEditorGameWorld.setStoryText();
        jButtonFinishGame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogChooseRegion = new javax.swing.JDialog();
        jLabelCountRegion = new javax.swing.JLabel();
        jLabelDesert = new javax.swing.JLabel();
        jLabelTundra = new javax.swing.JLabel();
        jLabelMixedForest = new javax.swing.JLabel();
        jButtonChooseRegion = new javax.swing.JButton();
        jComboBoxTundra = new javax.swing.JComboBox<>();
        jComboBoxMixedForest = new javax.swing.JComboBox<>();
        jComboBoxDesert = new javax.swing.JComboBox<>();
        jFrameGame = new javax.swing.JFrame();
        jPanelGameTable = new javax.swing.JPanel();
        jScrollPaneRegions = new javax.swing.JScrollPane();
        jTableCurrentRegion = new javax.swing.JTable();
        jButtonCutTree = new javax.swing.JButton();
        jButtonBuildHouse = new javax.swing.JButton();
        jButtonBuildFire = new javax.swing.JButton();
        jButtonExitGame = new javax.swing.JButton();
        jButtonBuildWell = new javax.swing.JButton();
        jPanelGameTop = new javax.swing.JPanel();
        jButtonMap = new javax.swing.JButton();
        jLabelCurrentRegion = new javax.swing.JLabel();
        jButtonBag = new javax.swing.JButton();
        jPanelGameImage = new ImagePanel();
        jPanelMission = new javax.swing.JPanel();
        jLabelMission = new javax.swing.JLabel();
        jScrollPaneMission = new javax.swing.JScrollPane();
        jTextAreaDesription = new javax.swing.JTextArea();
        jLabelTaskProgress = new javax.swing.JLabel();
        jLabelTaskName = new javax.swing.JLabel();
        jLabelMissionComplete = new javax.swing.JLabel();
        jLabelTask = new javax.swing.JLabel();
        jButtonFinishGame = new javax.swing.JButton();
        jDialogMap = new javax.swing.JDialog();
        jLabelMap = new javax.swing.JLabel();
        jScrollPaneMap = new javax.swing.JScrollPane();
        jListMap = new javax.swing.JList<>();
        jButtonChooseCurrentRegion = new javax.swing.JButton();
        jButtonCloseMap = new javax.swing.JButton();
        jDialogBag = new javax.swing.JDialog();
        jPanelBag = new javax.swing.JPanel();
        jLabelBag = new javax.swing.JLabel();
        jScrollPaneItems = new javax.swing.JScrollPane();
        jListItems = new javax.swing.JList<>();
        jButtonItemsOk = new javax.swing.JButton();
        jDialogBeginStory = new javax.swing.JDialog();
        jLabelBigining = new javax.swing.JLabel();
        jScrollPaneBeginStory = new javax.swing.JScrollPane();
        jTextAreaBeginStory = new javax.swing.JTextArea();
        jButtonContinueGame = new javax.swing.JButton();
        jDialogEndStory = new javax.swing.JDialog();
        jLabelBigining1 = new javax.swing.JLabel();
        jButtonFinishGameWin = new javax.swing.JButton();
        jScrollPaneEndStory = new javax.swing.JScrollPane();
        jTextAreaEndStory = new javax.swing.JTextArea();
        jPanelStartGame = new javax.swing.JPanel();
        jLabelGame = new javax.swing.JLabel();
        jLabelImageGame = new javax.swing.JLabel();
        jButtonStartGame = new javax.swing.JButton();

        jDialogChooseRegion.setBackground(new java.awt.Color(222, 236, 252));

        jLabelCountRegion.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelCountRegion.setForeground(new java.awt.Color(234, 114, 246));
        jLabelCountRegion.setText("Выберите кол-во регионов:");

        jLabelDesert.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelDesert.setForeground(new java.awt.Color(114, 158, 246));
        jLabelDesert.setText("Пустыня");

        jLabelTundra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTundra.setForeground(new java.awt.Color(114, 158, 246));
        jLabelTundra.setText("Тундра");

        jLabelMixedForest.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMixedForest.setForeground(new java.awt.Color(114, 158, 246));
        jLabelMixedForest.setText("Смешанный лес");

        this.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/Лого.png")).getImage());
        jFrameGame.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/Лого.png")).getImage());
        jLabelImageGame.setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/Логотип.png")));

        int numbers_to_add_max = 50;
        for (int i = 1; i <= numbers_to_add_max; i++ ) {
            jComboBoxTundra.addItem(String.valueOf(i));
            jComboBoxMixedForest.addItem(String.valueOf(i));
            jComboBoxDesert.addItem(String.valueOf(i));
        }

        jButtonChooseRegion.setText("Выбрать");
        jButtonChooseRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogChooseRegionLayout = new javax.swing.GroupLayout(jDialogChooseRegion.getContentPane());
        jDialogChooseRegion.getContentPane().setLayout(jDialogChooseRegionLayout);
        jDialogChooseRegionLayout.setHorizontalGroup(
                jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabelCountRegion)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabelTundra)
                                .addGap(0, 88, Short.MAX_VALUE)
                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelMixedForest)
                                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jButtonChooseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(79, 79, 79)
                                .addComponent(jLabelDesert)
                                .addGap(47, 47, 47))
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jComboBoxTundra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173)
                                .addComponent(jComboBoxMixedForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxDesert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
        );
        jDialogChooseRegionLayout.setVerticalGroup(
                jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabelCountRegion)
                                .addGap(72, 72, 72)
                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelTundra)
                                        .addComponent(jLabelMixedForest)
                                        .addComponent(jLabelDesert))
                                .addGap(18, 18, 18)
                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxTundra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxMixedForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxDesert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(jButtonChooseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
        );

        jFrameGame.setBackground(new java.awt.Color(222, 236, 252));

        jTableCurrentRegion.setBorder(new javax.swing.border.MatteBorder(null));
        jTableCurrentRegion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableCurrentRegion.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
        ));
        jTableCurrentRegion.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableCurrentRegion.getTableHeader().setReorderingAllowed(false);
        jScrollPaneRegions.setViewportView(jTableCurrentRegion);

        jButtonCutTree.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCutTree.setText("Срубить дерево");
        jButtonCutTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCutTreeActionPerformed(evt);
            }
        });

        jButtonBuildHouse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuildHouse.setText("Построить дом");
        jButtonBuildHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildHouseActionPerformed(evt);
            }
        });

        jButtonBuildFire.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuildFire.setText("Разжечь костер");
        jButtonBuildFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildFireActionPerformed(evt);
            }
        });

        jButtonExitGame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExitGame.setText("Выйти");
        jButtonExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitGameActionPerformed(evt);
            }
        });

        jButtonBuildWell.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuildWell.setText("Построить колодец");
        jButtonBuildWell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildWellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGameTableLayout = new javax.swing.GroupLayout(jPanelGameTable);
        jPanelGameTable.setLayout(jPanelGameTableLayout);
        jPanelGameTableLayout.setHorizontalGroup(
                jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGameTableLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPaneRegions)
                                        .addGroup(jPanelGameTableLayout.createSequentialGroup()
                                                .addComponent(jButtonCutTree)
                                                .addGap(28, 28, 28)
                                                .addComponent(jButtonBuildHouse)
                                                .addGap(51, 51, 51)
                                                .addComponent(jButtonBuildFire)
                                                .addGap(48, 48, 48)
                                                .addComponent(jButtonBuildWell)
                                                .addGap(310, 310, 310)
                                                .addComponent(jButtonExitGame)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGameTableLayout.setVerticalGroup(
                jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGameTableLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPaneRegions, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonCutTree, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBuildHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBuildFire, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBuildWell, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonExitGame, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtonMap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMap.setText("Карта");
        jButtonMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapActionPerformed(evt);
            }
        });

        jLabelCurrentRegion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelCurrentRegion.setForeground(new java.awt.Color(114, 158, 246));

        jButtonBag.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBag.setText("Сумка");
        jButtonBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGameTopLayout = new javax.swing.GroupLayout(jPanelGameTop);
        jPanelGameTop.setLayout(jPanelGameTopLayout);
        jPanelGameTopLayout.setHorizontalGroup(
                jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGameTopLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButtonBag)
                                .addGap(293, 293, 293)
                                .addComponent(jLabelCurrentRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonMap)
                                .addGap(40, 40, 40))
        );
        jPanelGameTopLayout.setVerticalGroup(
                jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGameTopLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelGameTopLayout.createSequentialGroup()
                                                .addGroup(jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelCurrentRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonBag, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanelGameImageLayout = new javax.swing.GroupLayout(jPanelGameImage);
        jPanelGameImage.setLayout(jPanelGameImageLayout);
        jPanelGameImageLayout.setHorizontalGroup(
                jPanelGameImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanelGameImageLayout.setVerticalGroup(
                jPanelGameImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 355, Short.MAX_VALUE)
        );

        jPanelMission.setForeground(new java.awt.Color(51, 255, 51));
        jPanelMission.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jLabelMission.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelMission.setForeground(new java.awt.Color(246, 154, 114));
        jLabelMission.setText("Миссия");

        jTextAreaDesription.setColumns(20);
        jTextAreaDesription.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextAreaDesription.setRows(5);
        jScrollPaneMission.setViewportView(jTextAreaDesription);

        jLabelTaskProgress.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelTaskName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTaskName.setForeground(new java.awt.Color(246, 154, 114));
        jLabelTaskName.setText("Задание");

        jLabelMissionComplete.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelMissionComplete.setForeground(new java.awt.Color(51, 255, 51));

        jLabelTask.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButtonFinishGame.setBackground(new java.awt.Color(204, 0, 204));
        jButtonFinishGame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFinishGame.setText("Закончить приключение");
        jButtonFinishGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMissionLayout = new javax.swing.GroupLayout(jPanelMission);
        jPanelMission.setLayout(jPanelMissionLayout);
        jPanelMissionLayout.setHorizontalGroup(
                jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                .addGroup(jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addComponent(jLabelMission)
                                                .addGap(0, 93, Short.MAX_VALUE))
                                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPaneMission))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMissionLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jLabelTaskName))
                                                        .addComponent(jLabelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelTaskProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMissionLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMissionLayout.createSequentialGroup()
                                                .addComponent(jLabelMissionComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMissionLayout.createSequentialGroup()
                                                .addComponent(jButtonFinishGame)
                                                .addGap(54, 54, 54))))
        );
        jPanelMissionLayout.setVerticalGroup(
                jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabelMission, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneMission, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelTask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelTaskProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabelMissionComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jButtonFinishGame, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jFrameGameLayout = new javax.swing.GroupLayout(jFrameGame.getContentPane());
        jFrameGame.getContentPane().setLayout(jFrameGameLayout);
        jFrameGameLayout.setHorizontalGroup(
                jFrameGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrameGameLayout.createSequentialGroup()
                                .addGroup(jFrameGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelGameTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelGameTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jFrameGameLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jPanelGameImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrameGameLayout.setVerticalGroup(
                jFrameGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrameGameLayout.createSequentialGroup()
                                .addComponent(jPanelGameTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelGameImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelGameTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanelMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialogMap.setBackground(new java.awt.Color(222, 236, 252));

        jLabelMap.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelMap.setForeground(new java.awt.Color(114, 158, 246));
        jLabelMap.setText("Карта мира");

        jListMap.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneMap.setViewportView(jListMap);

        jButtonChooseCurrentRegion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonChooseCurrentRegion.setText("Перейти");
        jButtonChooseCurrentRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseCurrentRegionActionPerformed(evt);
            }
        });

        jButtonCloseMap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCloseMap.setText("Закрыть");
        jButtonCloseMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogMapLayout = new javax.swing.GroupLayout(jDialogMap.getContentPane());
        jDialogMap.getContentPane().setLayout(jDialogMapLayout);
        jDialogMapLayout.setHorizontalGroup(
                jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jButtonChooseCurrentRegion)
                                .addGap(251, 251, 251)
                                .addComponent(jButtonCloseMap)
                                .addGap(71, 89, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogMapLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogMapLayout.createSequentialGroup()
                                                .addComponent(jScrollPaneMap, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(79, 79, 79))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogMapLayout.createSequentialGroup()
                                                .addComponent(jLabelMap)
                                                .addGap(225, 225, 225))))
        );
        jDialogMapLayout.setVerticalGroup(
                jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabelMap)
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPaneMap, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonChooseCurrentRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCloseMap, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogBag.setBackground(new java.awt.Color(222, 236, 252));

        jLabelBag.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelBag.setForeground(new java.awt.Color(114, 158, 246));
        jLabelBag.setText("Предметы");

        jScrollPaneItems.setViewportView(jListItems);

        jButtonItemsOk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonItemsOk.setText("ОК");
        jButtonItemsOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItemsOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBagLayout = new javax.swing.GroupLayout(jPanelBag);
        jPanelBag.setLayout(jPanelBagLayout);
        jPanelBagLayout.setHorizontalGroup(
                jPanelBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                .addGroup(jPanelBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                                .addGap(242, 242, 242)
                                                .addComponent(jButtonItemsOk, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                                .addGap(133, 133, 133)
                                                .addComponent(jScrollPaneItems, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                                .addGap(209, 209, 209)
                                                .addComponent(jLabelBag)))
                                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanelBagLayout.setVerticalGroup(
                jPanelBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabelBag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jScrollPaneItems, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonItemsOk, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogBagLayout = new javax.swing.GroupLayout(jDialogBag.getContentPane());
        jDialogBag.getContentPane().setLayout(jDialogBagLayout);
        jDialogBagLayout.setHorizontalGroup(
                jDialogBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelBag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogBagLayout.setVerticalGroup(
                jDialogBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelBag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialogBeginStory.setBackground(new java.awt.Color(222, 236, 252));

        jLabelBigining.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabelBigining.setForeground(new java.awt.Color(114, 158, 246));
        jLabelBigining.setText("Начало");

        jTextAreaBeginStory.setEditable(false);
        jTextAreaBeginStory.setColumns(20);
        jTextAreaBeginStory.setRows(5);
        jScrollPaneBeginStory.setViewportView(jTextAreaBeginStory);

        jButtonContinueGame.setText("Вперед");
        jButtonContinueGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogBeginStoryLayout = new javax.swing.GroupLayout(jDialogBeginStory.getContentPane());
        jDialogBeginStory.getContentPane().setLayout(jDialogBeginStoryLayout);
        jDialogBeginStoryLayout.setHorizontalGroup(
                jDialogBeginStoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogBeginStoryLayout.createSequentialGroup()
                                .addGroup(jDialogBeginStoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jDialogBeginStoryLayout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(jScrollPaneBeginStory, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jDialogBeginStoryLayout.createSequentialGroup()
                                                .addGap(310, 310, 310)
                                                .addComponent(jButtonContinueGame, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jDialogBeginStoryLayout.createSequentialGroup()
                                                .addGap(298, 298, 298)
                                                .addComponent(jLabelBigining)))
                                .addContainerGap(76, Short.MAX_VALUE))
        );
        jDialogBeginStoryLayout.setVerticalGroup(
                jDialogBeginStoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogBeginStoryLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabelBigining)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jScrollPaneBeginStory, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButtonContinueGame, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
        );

        jDialogEndStory.setBackground(new java.awt.Color(222, 236, 252));

        jLabelBigining1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabelBigining1.setForeground(new java.awt.Color(114, 158, 246));
        jLabelBigining1.setText("Поздравляем!");

        jButtonFinishGameWin.setText("Закончить игру");
        jButtonFinishGameWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishGameWinActionPerformed(evt);
            }
        });

        jTextAreaEndStory.setEditable(false);
        jTextAreaEndStory.setColumns(20);
        jTextAreaEndStory.setRows(5);
        jScrollPaneEndStory.setViewportView(jTextAreaEndStory);

        javax.swing.GroupLayout jDialogEndStoryLayout = new javax.swing.GroupLayout(jDialogEndStory.getContentPane());
        jDialogEndStory.getContentPane().setLayout(jDialogEndStoryLayout);
        jDialogEndStoryLayout.setHorizontalGroup(
                jDialogEndStoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogEndStoryLayout.createSequentialGroup()
                                .addGroup(jDialogEndStoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jDialogEndStoryLayout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(jScrollPaneEndStory, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jDialogEndStoryLayout.createSequentialGroup()
                                                .addGap(273, 273, 273)
                                                .addComponent(jButtonFinishGameWin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jDialogEndStoryLayout.createSequentialGroup()
                                                .addGap(224, 224, 224)
                                                .addComponent(jLabelBigining1)))
                                .addContainerGap(57, Short.MAX_VALUE))
        );
        jDialogEndStoryLayout.setVerticalGroup(
                jDialogEndStoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogEndStoryLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelBigining1)
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPaneEndStory, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonFinishGameWin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelStartGame.setForeground(new java.awt.Color(222, 236, 252));

        jLabelGame.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabelGame.setForeground(new java.awt.Color(111, 68, 193));
        jLabelGame.setText("\"Стрела судьбы\"");

        jButtonStartGame.setText("Начать");
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStartGameLayout = new javax.swing.GroupLayout(jPanelStartGame);
        jPanelStartGame.setLayout(jPanelStartGameLayout);
        jPanelStartGameLayout.setHorizontalGroup(
                jPanelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                .addGroup(jPanelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                                .addGap(265, 265, 265)
                                                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(jLabelImageGame, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(78, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStartGameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelGame)
                                .addGap(201, 201, 201))
        );
        jPanelStartGameLayout.setVerticalGroup(
                jPanelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabelGame)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelImageGame, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelStartGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jTextAreaDesription.setEditable(false);
        jTextAreaDesription.setLineWrap(true);
        jTextAreaDesription.setWrapStyleWord(true);
        jTextAreaDesription.setBorder(null);
        jTextAreaDesription.setFont(new java.awt.Font("Segoe UI", 0, 18));

        // Прозрачный задний фон
        jTextAreaDesription.setOpaque(false);
        jTextAreaDesription.setBackground(new java.awt.Color(0, 0, 0, 0));
        pack();
    }// </editor-fold>
    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartGameActionPerformed
        gameWorld = new GameWorld();
        initGameWorld();
        jDialogBeginStory.setVisible(true);
        jDialogBeginStory.setBounds(100, 100, 740, 460);
        ChangeScreenSize.setLocation(jDialogBeginStory);

    }//GEN-LAST:event_jButtonStartGameActionPerformed

    private void jButtonChooseRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseRegionActionPerformed

        try {
                takeCountRegions();
                cleanComboBox();

                textEditorGameWorld.updateCurrentRegion(gameWorld.getCurrentRegion(),gameWorld.getRegions());
                jDialogChooseRegion.dispose();
                jFrameGame.setVisible(rootPaneCheckingEnabled);
                jFrameGame.setSize(1490, 770);
                ChangeScreenSize.setLocation(jFrameGame);

        } catch (Exception e) {
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonChooseRegionActionPerformed

    private void cleanComboBox() {
        jComboBoxTundra.setSelectedIndex(0);
        jComboBoxMixedForest.setSelectedIndex(0);
        jComboBoxDesert.setSelectedIndex(0);
    }

    private void takeCountRegions() throws Exception {

        int countTundra =Integer.parseInt((String) jComboBoxTundra.getSelectedItem());
        int countMixedForest = Integer.parseInt((String) jComboBoxMixedForest.getSelectedItem());
        int countDesert = Integer.parseInt((String) jComboBoxDesert.getSelectedItem());

        gameWorld.createWorld(countTundra,countMixedForest,countDesert);
    }

    private void jButtonCutTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCutTreeActionPerformed
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.cutTree(chooseObject);
            textEditorGameWorld.updateCurrentRegion();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonCutTreeActionPerformed

    private void jButtonBuildHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuildHouseActionPerformed
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.buildHouse(chooseObject);
            textEditorGameWorld.updateCurrentRegion();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuildHouseActionPerformed

    private void jButtonBuildFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuildFireActionPerformed
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.buildFire(chooseObject);
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }finally {
            textEditorGameWorld.updateCurrentRegion();
        }
    }//GEN-LAST:event_jButtonBuildFireActionPerformed
    private void jButtonBuildWellActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.buildWell(chooseObject);
            textEditorGameWorld.updateCurrentRegion();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void jButtonExitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitGameActionPerformed
        jFrameGame.dispose();
    }//GEN-LAST:event_jButtonExitGameActionPerformed

    private void jButtonMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapActionPerformed
        jDialogMap.setVisible(true);
        jDialogMap.setBounds(100, 100, 655, 560);
        ChangeScreenSize.setLocation(jDialogMap);
        textEditorGameWorld.setModelMap(gameWorld.getRegions(), gameWorld.getCurrentRegion());
    }//GEN-LAST:event_jButtonMapActionPerformed

    private void jButtonChooseCurrentRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseCurrentRegionActionPerformed
        try{
            int chooseObject = jListMap.getSelectedIndex();
            gameWorld.changeCurrentRegion(chooseObject);
            textEditorGameWorld.updateCurrentRegion(gameWorld.getCurrentRegion());
            jDialogMap.dispose();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonChooseCurrentRegionActionPerformed

    private void jButtonCloseMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseMapActionPerformed
        jDialogMap.dispose();
    }//GEN-LAST:event_jButtonCloseMapActionPerformed
    private void jButtonBagActionPerformed(java.awt.event.ActionEvent evt) {
        textEditorGameWorld.setModelMap(gameWorld.getPlayer());
        jDialogBag.setVisible(true);
        jDialogBag.setBounds(100, 100, 570, 470);
        ChangeScreenSize.setLocation(jDialogBag);
    }
    private void jButtonContinueGameActionPerformed(java.awt.event.ActionEvent evt) {
        jDialogBeginStory.dispose();

        jDialogChooseRegion.setVisible(true);
        jDialogChooseRegion.setBounds(0, 100, 645, 399);
        ChangeScreenSize.setLocation(jDialogChooseRegion);
    }

    private void jButtonItemsOkActionPerformed(java.awt.event.ActionEvent evt) {
        jDialogBag.dispose();
    }
    private void jButtonFinishGameActionPerformed(java.awt.event.ActionEvent evt) {
        jFrameGame.dispose();
        jDialogEndStory.setVisible(true);
        jDialogEndStory.setBounds(100, 100, 740, 460);
        ChangeScreenSize.setLocation(jDialogEndStory);
    }
    private void jButtonFinishGameWinActionPerformed(java.awt.event.ActionEvent evt) {
        jDialogEndStory.dispose();
    }

    private javax.swing.JButton jButtonBag;
    private javax.swing.JButton jButtonBuildFire;
    private javax.swing.JButton jButtonBuildHouse;
    private javax.swing.JButton jButtonBuildWell;
    private javax.swing.JButton jButtonChooseCurrentRegion;
    private javax.swing.JButton jButtonChooseRegion;
    private javax.swing.JButton jButtonCloseMap;
    private javax.swing.JButton jButtonContinueGame;
    private javax.swing.JButton jButtonCutTree;
    private javax.swing.JButton jButtonExitGame;
    private javax.swing.JButton jButtonFinishGame;
    private javax.swing.JButton jButtonFinishGameWin;
    private javax.swing.JButton jButtonItemsOk;
    private javax.swing.JButton jButtonMap;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JComboBox<String> jComboBoxDesert;
    private javax.swing.JComboBox<String> jComboBoxMixedForest;
    private javax.swing.JComboBox<String> jComboBoxTundra;
    private javax.swing.JDialog jDialogBag;
    private javax.swing.JDialog jDialogBeginStory;
    private javax.swing.JDialog jDialogChooseRegion;
    private javax.swing.JDialog jDialogEndStory;
    private javax.swing.JDialog jDialogMap;
    private javax.swing.JFrame jFrameGame;
    private javax.swing.JLabel jLabelBag;
    private javax.swing.JLabel jLabelBigining;
    private javax.swing.JLabel jLabelBigining1;
    private javax.swing.JLabel jLabelCountRegion;
    private javax.swing.JLabel jLabelCurrentRegion;
    private javax.swing.JLabel jLabelDesert;
    private javax.swing.JLabel jLabelGame;
    private javax.swing.JLabel jLabelImageGame;
    private javax.swing.JLabel jLabelMap;
    private javax.swing.JLabel jLabelMission;
    private javax.swing.JLabel jLabelMissionComplete;
    private javax.swing.JLabel jLabelMixedForest;
    private javax.swing.JLabel jLabelTask;
    private javax.swing.JLabel jLabelTaskName;
    private javax.swing.JLabel jLabelTaskProgress;
    private javax.swing.JLabel jLabelTundra;
    private javax.swing.JList<String> jListItems;
    private javax.swing.JList<String> jListMap;
    private javax.swing.JPanel jPanelBag;
    private ImagePanel jPanelGameImage;
    private javax.swing.JPanel jPanelGameTable;
    private javax.swing.JPanel jPanelGameTop;
    private javax.swing.JPanel jPanelMission;
    private javax.swing.JPanel jPanelStartGame;
    private javax.swing.JScrollPane jScrollPaneBeginStory;
    private javax.swing.JScrollPane jScrollPaneEndStory;
    private javax.swing.JScrollPane jScrollPaneItems;
    private javax.swing.JScrollPane jScrollPaneMap;
    private javax.swing.JScrollPane jScrollPaneMission;
    private javax.swing.JScrollPane jScrollPaneRegions;
    private javax.swing.JTable jTableCurrentRegion;
    private javax.swing.JTextArea jTextAreaBeginStory;
    private javax.swing.JTextArea jTextAreaDesription;
    private javax.swing.JTextArea jTextAreaEndStory;
    // End of variables declaration
}
