/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example;

import org.example.editors.TextEditorGameWorld;
import org.example.missionsFactory.TundraMissionFactory;

import javax.swing.*;
import java.awt.*;


/**
 *
 * @author kzsbv
 */
public class Program extends javax.swing.JFrame {

    private GameWorld gameWorld = new GameWorld();
    private TextEditorGameWorld textEditorGameWorld;
    private Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

    public Program() {
        initComponents();
        initGameWorld();
        int numbers_to_add_max = 50;
        for (int i = 0; i <= numbers_to_add_max; i++ ) {
            jComboBoxTundra.addItem(String.valueOf(i));
            jComboBoxMixedForest.addItem(String.valueOf(i));
            jComboBoxDesert.addItem(String.valueOf(i));
        }
        jLabelImageGame.setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/Логотип.png")));
        jTableCurrentRegion.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        setLocation(this);

        jTextAreaDesription.setEditable(false);
        jTextAreaDesription.setLineWrap(true);
        jTextAreaDesription.setWrapStyleWord(true);
        jTextAreaDesription.setBorder(null);
        jTextAreaDesription.setFont(new java.awt.Font("Segoe UI", 0, 18));

        // Прозрачный задний фон
        jTextAreaDesription.setOpaque(false);
        jTextAreaDesription.setBackground(new java.awt.Color(0, 0, 0, 0));

        new TundraMissionFactory();
    }

    private void initGameWorld() {
        textEditorGameWorld = new TextEditorGameWorld(jLabelCurrentRegion,jTableCurrentRegion, jPanelGameImage);
        textEditorGameWorld.createTextEditorMap(jListMap);
        textEditorGameWorld.createTextEditorBag(jListItems);
        textEditorGameWorld.createTextEditorMission(jTextAreaDesription, jLabelTask, jLabelTaskProgress,jLabelMissionComplete, gameWorld.getPlayer(),jButtonFinishGame);
        jButtonFinishGame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogChooseRegion = new javax.swing.JDialog();
        jLabelCountRegion = new javax.swing.JLabel();
        jLabelDesert = new javax.swing.JLabel();
        jLabelTundra = new javax.swing.JLabel();
        jLabelMixedForest = new javax.swing.JLabel();
        jButtonChooseRegion = new javax.swing.JButton();
        jComboBoxTundra = new javax.swing.JComboBox<>();
        jComboBoxMixedForest = new javax.swing.JComboBox<>();
        jComboBoxDesert = new javax.swing.JComboBox<>();
        jFrameGame = new javax.swing.JFrame();
        jPanelGameTable = new javax.swing.JPanel();
        jScrollPaneRegions = new javax.swing.JScrollPane();
        jTableCurrentRegion = new javax.swing.JTable();
        jButtonCutTree = new javax.swing.JButton();
        jButtonBuildHouse = new javax.swing.JButton();
        jButtonBuildFire = new javax.swing.JButton();
        jButtonExitGame = new javax.swing.JButton();
        jButtonBuildWell = new javax.swing.JButton();
        jPanelGameTop = new javax.swing.JPanel();
        jButtonMap = new javax.swing.JButton();
        jLabelCurrentRegion = new javax.swing.JLabel();
        jButtonBag = new javax.swing.JButton();
        jPanelGameImage = new ImagePanel();
        jPanelMission = new javax.swing.JPanel();
        jLabelMission = new javax.swing.JLabel();
        jScrollPaneMission = new javax.swing.JScrollPane();
        jTextAreaDesription = new javax.swing.JTextArea();
        jLabelTaskProgress = new javax.swing.JLabel();
        jLabelTaskName = new javax.swing.JLabel();
        jLabelMissionComplete = new javax.swing.JLabel();
        jLabelTask = new javax.swing.JLabel();
        jButtonFinishGame = new javax.swing.JButton();
        jDialogMap = new javax.swing.JDialog();
        jLabelMap = new javax.swing.JLabel();
        jScrollPaneMap = new javax.swing.JScrollPane();
        jListMap = new javax.swing.JList<>();
        jLabelImageMap = new javax.swing.JLabel();
        jButtonChooseCurrentRegion = new javax.swing.JButton();
        jButtonCloseMap = new javax.swing.JButton();
        jDialogBag = new javax.swing.JDialog();
        jPanelBag = new javax.swing.JPanel();
        jLabelBag = new javax.swing.JLabel();
        jScrollPaneItems = new javax.swing.JScrollPane();
        jListItems = new javax.swing.JList<>();
        jButtonItemsOk = new javax.swing.JButton();
        jPanelStartGame = new javax.swing.JPanel();
        jLabelGame = new javax.swing.JLabel();
        jLabelImageGame = new javax.swing.JLabel();
        jButtonStartGame = new javax.swing.JButton();

        jLabelCountRegion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCountRegion.setText("Выберите кол-во регионов:");

        jLabelDesert.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelDesert.setText("Пустыня");

        jLabelTundra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTundra.setText("Тундра");

        jLabelMixedForest.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelMixedForest.setText("Смешанный лес");

        jButtonChooseRegion.setText("Выбрать");
        jButtonChooseRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogChooseRegionLayout = new javax.swing.GroupLayout(jDialogChooseRegion.getContentPane());
        jDialogChooseRegion.getContentPane().setLayout(jDialogChooseRegionLayout);
        jDialogChooseRegionLayout.setHorizontalGroup(
                jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabelCountRegion)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabelTundra)
                                .addGap(0, 118, Short.MAX_VALUE)
                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonChooseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelMixedForest))
                                .addGap(79, 79, 79)
                                .addComponent(jLabelDesert)
                                .addGap(47, 47, 47))
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jComboBoxTundra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxMixedForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192)
                                .addComponent(jComboBoxDesert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
        );
        jDialogChooseRegionLayout.setVerticalGroup(
                jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabelCountRegion)
                                .addGap(72, 72, 72)
                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelTundra)
                                        .addComponent(jLabelMixedForest)
                                        .addComponent(jLabelDesert))
                                .addGap(18, 18, 18)
                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxTundra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxMixedForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxDesert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(jButtonChooseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
        );

        jTableCurrentRegion.setBorder(new javax.swing.border.MatteBorder(null));
        jTableCurrentRegion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableCurrentRegion.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
        ));
        jTableCurrentRegion.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableCurrentRegion.getTableHeader().setReorderingAllowed(false);
        jScrollPaneRegions.setViewportView(jTableCurrentRegion);

        jButtonCutTree.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCutTree.setText("Срубить дерево");
        jButtonCutTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCutTreeActionPerformed(evt);
            }
        });

        jButtonBuildHouse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuildHouse.setText("Построить дом");
        jButtonBuildHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildHouseActionPerformed(evt);
            }
        });

        jButtonBuildFire.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuildFire.setText("Разжечь костер");
        jButtonBuildFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildFireActionPerformed(evt);
            }
        });

        jButtonExitGame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExitGame.setText("Выйти");
        jButtonExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitGameActionPerformed(evt);
            }
        });

        jButtonBuildWell.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuildWell.setText("Построить колодец");
        jButtonBuildWell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildWellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGameTableLayout = new javax.swing.GroupLayout(jPanelGameTable);
        jPanelGameTable.setLayout(jPanelGameTableLayout);
        jPanelGameTableLayout.setHorizontalGroup(
                jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGameTableLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPaneRegions)
                                        .addGroup(jPanelGameTableLayout.createSequentialGroup()
                                                .addComponent(jButtonCutTree)
                                                .addGap(28, 28, 28)
                                                .addComponent(jButtonBuildHouse)
                                                .addGap(51, 51, 51)
                                                .addComponent(jButtonBuildFire)
                                                .addGap(48, 48, 48)
                                                .addComponent(jButtonBuildWell)
                                                .addGap(310, 310, 310)
                                                .addComponent(jButtonExitGame)))
                                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanelGameTableLayout.setVerticalGroup(
                jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGameTableLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPaneRegions, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonCutTree, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBuildHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBuildFire, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBuildWell, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonExitGame, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtonMap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMap.setText("Карта");
        jButtonMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapActionPerformed(evt);
            }
        });

        jLabelCurrentRegion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jButtonBag.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBag.setText("Сумка");
        jButtonBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGameTopLayout = new javax.swing.GroupLayout(jPanelGameTop);
        jPanelGameTop.setLayout(jPanelGameTopLayout);
        jPanelGameTopLayout.setHorizontalGroup(
                jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGameTopLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButtonBag)
                                .addGap(293, 293, 293)
                                .addComponent(jLabelCurrentRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonMap)
                                .addGap(40, 40, 40))
        );
        jPanelGameTopLayout.setVerticalGroup(
                jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGameTopLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelGameTopLayout.createSequentialGroup()
                                                .addGroup(jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelCurrentRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonBag, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanelGameImageLayout = new javax.swing.GroupLayout(jPanelGameImage);
        jPanelGameImage.setLayout(jPanelGameImageLayout);
        jPanelGameImageLayout.setHorizontalGroup(
                jPanelGameImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanelGameImageLayout.setVerticalGroup(
                jPanelGameImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 355, Short.MAX_VALUE)
        );

        jPanelMission.setForeground(new java.awt.Color(51, 255, 51));
        jPanelMission.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jLabelMission.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelMission.setText("Миссия");

        jTextAreaDesription.setColumns(20);
        jTextAreaDesription.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextAreaDesription.setRows(5);
        jScrollPaneMission.setViewportView(jTextAreaDesription);

        jLabelTaskProgress.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelTaskName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTaskName.setText("Задание");

        jLabelMissionComplete.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelMissionComplete.setForeground(new java.awt.Color(51, 255, 51));

        jLabelTask.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButtonFinishGame.setBackground(new java.awt.Color(204, 0, 204));
        jButtonFinishGame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFinishGame.setText("Закончить приключение");
        jButtonFinishGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMissionLayout = new javax.swing.GroupLayout(jPanelMission);
        jPanelMission.setLayout(jPanelMissionLayout);
        jPanelMissionLayout.setHorizontalGroup(
                jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                .addGroup(jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addComponent(jLabelMission)
                                                .addGap(0, 100, Short.MAX_VALUE))
                                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPaneMission))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMissionLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jLabelTaskName))
                                                        .addComponent(jLabelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelTaskProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMissionLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMissionLayout.createSequentialGroup()
                                                .addComponent(jLabelMissionComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMissionLayout.createSequentialGroup()
                                                .addComponent(jButtonFinishGame)
                                                .addGap(50, 50, 50))))
        );
        jPanelMissionLayout.setVerticalGroup(
                jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMissionLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabelMission, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneMission, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelTask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelTaskProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabelMissionComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jButtonFinishGame, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jFrameGameLayout = new javax.swing.GroupLayout(jFrameGame.getContentPane());
        jFrameGame.getContentPane().setLayout(jFrameGameLayout);
        jFrameGameLayout.setHorizontalGroup(
                jFrameGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrameGameLayout.createSequentialGroup()
                                .addGroup(jFrameGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelGameTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelGameTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jFrameGameLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jPanelGameImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrameGameLayout.setVerticalGroup(
                jFrameGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrameGameLayout.createSequentialGroup()
                                .addComponent(jPanelGameTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelGameImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelGameTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanelMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelMap.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelMap.setText("Карта мира");

        jListMap.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneMap.setViewportView(jListMap);

        jButtonChooseCurrentRegion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonChooseCurrentRegion.setText("Перейти");
        jButtonChooseCurrentRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseCurrentRegionActionPerformed(evt);
            }
        });

        jButtonCloseMap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCloseMap.setText("Закрыть");
        jButtonCloseMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogMapLayout = new javax.swing.GroupLayout(jDialogMap.getContentPane());
        jDialogMap.getContentPane().setLayout(jDialogMapLayout);
        jDialogMapLayout.setHorizontalGroup(
                jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                .addGroup(jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                                .addGap(253, 253, 253)
                                                .addComponent(jLabelMap))
                                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addGroup(jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPaneMap, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelImageMap, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jButtonChooseCurrentRegion)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButtonCloseMap)
                                                                .addGap(11, 11, 11)))))
                                .addGap(60, 78, Short.MAX_VALUE))
        );
        jDialogMapLayout.setVerticalGroup(
                jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMap)
                                .addGap(28, 28, 28)
                                .addComponent(jLabelImageMap, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneMap, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonChooseCurrentRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCloseMap, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelBag.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelBag.setText("Предметы");

        jScrollPaneItems.setViewportView(jListItems);

        jButtonItemsOk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonItemsOk.setText("ОК");
        jButtonItemsOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItemsOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBagLayout = new javax.swing.GroupLayout(jPanelBag);
        jPanelBag.setLayout(jPanelBagLayout);
        jPanelBagLayout.setHorizontalGroup(
                jPanelBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                .addGroup(jPanelBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                                .addGap(218, 218, 218)
                                                .addComponent(jLabelBag))
                                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                                .addGap(134, 134, 134)
                                                .addComponent(jScrollPaneItems, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                                .addGap(242, 242, 242)
                                                .addComponent(jButtonItemsOk, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanelBagLayout.setVerticalGroup(
                jPanelBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelBagLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelBag)
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPaneItems, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonItemsOk, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogBagLayout = new javax.swing.GroupLayout(jDialogBag.getContentPane());
        jDialogBag.getContentPane().setLayout(jDialogBagLayout);
        jDialogBagLayout.setHorizontalGroup(
                jDialogBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelBag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogBagLayout.setVerticalGroup(
                jDialogBagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelBag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelGame.setText("Game");

        jButtonStartGame.setText("Начать");
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStartGameLayout = new javax.swing.GroupLayout(jPanelStartGame);
        jPanelStartGame.setLayout(jPanelStartGameLayout);
        jPanelStartGameLayout.setHorizontalGroup(
                jPanelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                .addGroup(jPanelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                                .addGap(277, 277, 277)
                                                .addComponent(jLabelGame))
                                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                                .addGap(265, 265, 265)
                                                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(jLabelImageGame, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanelStartGameLayout.setVerticalGroup(
                jPanelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabelGame)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelImageGame, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelStartGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartGameActionPerformed
        gameWorld = new GameWorld();
        initGameWorld();

        jDialogChooseRegion.setVisible(true);
        jDialogChooseRegion.setBounds(0, 100, 645, 399);
        setLocation(jDialogChooseRegion);
    }//GEN-LAST:event_jButtonStartGameActionPerformed

    private void jButtonChooseRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseRegionActionPerformed

        try {
                takeCountRegions();
                cleanComboBox();

                textEditorGameWorld.updateCurrentRegion(gameWorld.getCurrentRegion(),gameWorld.getRegions());
                jDialogChooseRegion.dispose();
                jFrameGame.setVisible(rootPaneCheckingEnabled);
                jFrameGame.setSize(1490, 770);
                setLocation(jFrameGame);

        } catch (Exception e) {
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonChooseRegionActionPerformed

    private void cleanComboBox() {
        jComboBoxTundra.setSelectedIndex(0);
        jComboBoxMixedForest.setSelectedIndex(0);
        jComboBoxDesert.setSelectedIndex(0);
    }

    private void takeCountRegions() throws Exception {

        int countTundra = jComboBoxTundra.getSelectedIndex();
        int countMixedForest = jComboBoxMixedForest.getSelectedIndex();
        int countDesert = jComboBoxDesert.getSelectedIndex();

        gameWorld.createWorld(countTundra,countMixedForest,countDesert);
    }

    private void jButtonCutTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCutTreeActionPerformed
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.cutTree(chooseObject);
            textEditorGameWorld.updateCurrentRegion();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonCutTreeActionPerformed

    private void jButtonBuildHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuildHouseActionPerformed
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.buildHouse(chooseObject);
            textEditorGameWorld.updateCurrentRegion();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuildHouseActionPerformed

    private void jButtonBuildFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuildFireActionPerformed
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.buildFire(chooseObject);
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }finally {
            textEditorGameWorld.updateCurrentRegion();
        }
    }//GEN-LAST:event_jButtonBuildFireActionPerformed
    private void jButtonBuildWellActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.buildWell(chooseObject);
            textEditorGameWorld.updateCurrentRegion();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void jButtonExitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitGameActionPerformed
        jFrameGame.dispose();
    }//GEN-LAST:event_jButtonExitGameActionPerformed

    private void jButtonMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapActionPerformed
        jDialogMap.setVisible(true);
        jDialogMap.setBounds(100, 100, 655, 560);
        setLocation(jDialogMap);
        textEditorGameWorld.setModelMap(gameWorld.getRegions(), gameWorld.getCurrentRegion());
    }//GEN-LAST:event_jButtonMapActionPerformed

    private void jButtonChooseCurrentRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseCurrentRegionActionPerformed
        try{
            int chooseObject = jListMap.getSelectedIndex();
            gameWorld.changeCurrentRegion(chooseObject);
            textEditorGameWorld.updateCurrentRegion(gameWorld.getCurrentRegion());
            jDialogMap.dispose();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonChooseCurrentRegionActionPerformed

    private void jButtonCloseMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseMapActionPerformed
        jDialogMap.dispose();
    }//GEN-LAST:event_jButtonCloseMapActionPerformed
    private void jButtonBagActionPerformed(java.awt.event.ActionEvent evt) {
        textEditorGameWorld.setModelMap(gameWorld.getPlayer());
        jDialogBag.setVisible(true);
        jDialogBag.setBounds(100, 100, 570, 470);
        setLocation(jDialogBag);
    }

    private void jButtonItemsOkActionPerformed(java.awt.event.ActionEvent evt) {
        jDialogBag.dispose();
    }
    private void jButtonFinishGameActionPerformed(java.awt.event.ActionEvent evt) {
        jFrameGame.dispose();
    }

    private void setLocation(JFrame frame){
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        // Вычисление координат для размещения окна в середине экрана
        int x = (screenWidth - frame.getWidth()) / 2;
        int y = (screenHeight - frame.getHeight()) / 2;

        // Установка позиции окна
        frame.setLocation(x, y);
    }
    private void setLocation(JDialog dialog){
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        // Вычисление координат для размещения окна в середине экрана
        int x = (screenWidth - dialog.getWidth()) / 2;
        int y = (screenHeight - dialog.getHeight()) / 2;

        // Установка позиции окна
        dialog.setLocation(x, y);
    }
    private javax.swing.JButton jButtonBag;
    private javax.swing.JButton jButtonBuildFire;
    private javax.swing.JButton jButtonBuildHouse;
    private javax.swing.JButton jButtonBuildWell;
    private javax.swing.JButton jButtonChooseCurrentRegion;
    private javax.swing.JButton jButtonChooseRegion;
    private javax.swing.JButton jButtonCloseMap;
    private javax.swing.JButton jButtonCutTree;
    private javax.swing.JButton jButtonExitGame;
    private javax.swing.JButton jButtonFinishGame;
    private javax.swing.JButton jButtonItemsOk;
    private javax.swing.JButton jButtonMap;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JComboBox<String> jComboBoxDesert;
    private javax.swing.JComboBox<String> jComboBoxMixedForest;
    private javax.swing.JComboBox<String> jComboBoxTundra;
    private javax.swing.JDialog jDialogBag;
    private javax.swing.JDialog jDialogChooseRegion;
    private javax.swing.JDialog jDialogMap;
    private javax.swing.JFrame jFrameGame;
    private javax.swing.JLabel jLabelBag;
    private javax.swing.JLabel jLabelCountRegion;
    private javax.swing.JLabel jLabelCurrentRegion;
    private javax.swing.JLabel jLabelDesert;
    private javax.swing.JLabel jLabelGame;
    private javax.swing.JLabel jLabelImageGame;
    private javax.swing.JLabel jLabelImageMap;
    private javax.swing.JLabel jLabelMap;
    private javax.swing.JLabel jLabelMission;
    private javax.swing.JLabel jLabelMissionComplete;
    private javax.swing.JLabel jLabelMixedForest;
    private javax.swing.JLabel jLabelTask;
    private javax.swing.JLabel jLabelTaskName;
    private javax.swing.JLabel jLabelTaskProgress;
    private javax.swing.JLabel jLabelTundra;
    private javax.swing.JList<String> jListItems;
    private javax.swing.JList<String> jListMap;
    private javax.swing.JPanel jPanelBag;
    private ImagePanel jPanelGameImage;
    private javax.swing.JPanel jPanelGameTable;
    private javax.swing.JPanel jPanelGameTop;
    private javax.swing.JPanel jPanelMission;
    private javax.swing.JPanel jPanelStartGame;
    private javax.swing.JScrollPane jScrollPaneItems;
    private javax.swing.JScrollPane jScrollPaneMap;
    private javax.swing.JScrollPane jScrollPaneMission;
    private javax.swing.JScrollPane jScrollPaneRegions;
    private javax.swing.JTable jTableCurrentRegion;
    private javax.swing.JTextArea jTextAreaDesription;
    // End of variables declaration
}
