/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author kzsbv
 */
public class Program extends javax.swing.JFrame {

    private GameWorld gameWorld = new GameWorld();
    private TextEditorGameWorld textEditorGameWorld;
    private TextEditorMap textEditorMap;

    public Program() {
        initComponents();
        textEditorGameWorld = new TextEditorGameWorld(jLabelCurrentRegion,jTableCurrentRegion, jPanelGameImage);
        textEditorMap = new TextEditorMap(jListMap);
        int numbers_to_add_max = 50;
        for (int i = 0; i <= numbers_to_add_max; i++ ) {
            jComboBoxTundra.addItem(String.valueOf(i));
            jComboBoxMixedForest.addItem(String.valueOf(i));
            jComboBoxDesert.addItem(String.valueOf(i));
        }
        jTableCurrentRegion.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogChooseRegion = new javax.swing.JDialog();
        jLabelCountRegion = new javax.swing.JLabel();
        jLabelDesert = new javax.swing.JLabel();
        jLabelTundra = new javax.swing.JLabel();
        jLabelMixedForest = new javax.swing.JLabel();
        jButtonChooseRegion = new javax.swing.JButton();
        jComboBoxTundra = new javax.swing.JComboBox<>();
        jComboBoxMixedForest = new javax.swing.JComboBox<>();
        jComboBoxDesert = new javax.swing.JComboBox<>();
        jFrameGame = new javax.swing.JFrame();
        jPanelGameTable = new javax.swing.JPanel();
        jScrollPaneRegions = new javax.swing.JScrollPane();
        jTableCurrentRegion = new javax.swing.JTable();
        jButtonCutTree = new javax.swing.JButton();
        jButtonBuildHouse = new javax.swing.JButton();
        jButtonBuildFire = new javax.swing.JButton();
        jButtonBuildWell = new javax.swing.JButton();
        jButtonExitGame = new javax.swing.JButton();
        jPanelGameTop = new javax.swing.JPanel();
        jButtonMap = new javax.swing.JButton();
        jLabelCurrentRegion = new javax.swing.JLabel();
        jPanelGameImage = new ImagePanel();
        jDialogMap = new javax.swing.JDialog();
        jLabelMap = new javax.swing.JLabel();
        jScrollPaneMap = new javax.swing.JScrollPane();
        jListMap = new javax.swing.JList<>();
        jLabelImageMap = new javax.swing.JLabel();
        jButtonChooseCurrentRegion = new javax.swing.JButton();
        jButtonCloseMap = new javax.swing.JButton();
        jPanelStartGame = new javax.swing.JPanel();
        jLabelGame = new javax.swing.JLabel();
        jLabelImageGame = new javax.swing.JLabel();
        jButtonStartGame = new javax.swing.JButton();

        jLabelCountRegion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCountRegion.setText("Выберите кол-во регионов:");

        jLabelDesert.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelDesert.setText("Пустыня");

        jLabelTundra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTundra.setText("Тундра");

        jLabelMixedForest.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelMixedForest.setText("Смешанный лес");

        jButtonChooseRegion.setText("Выбрать");
        jButtonChooseRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogChooseRegionLayout = new javax.swing.GroupLayout(jDialogChooseRegion.getContentPane());
        jDialogChooseRegion.getContentPane().setLayout(jDialogChooseRegionLayout);
        jDialogChooseRegionLayout.setHorizontalGroup(
                jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabelCountRegion)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                                .addComponent(jLabelTundra)
                                                .addGap(0, 118, Short.MAX_VALUE)
                                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButtonChooseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelMixedForest))
                                                .addGap(79, 79, 79)
                                                .addComponent(jLabelDesert)
                                                .addGap(47, 47, 47))
                                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                                .addComponent(jComboBoxTundra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(186, 186, 186)
                                                .addComponent(jComboBoxMixedForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBoxDesert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57))))
        );
        jDialogChooseRegionLayout.setVerticalGroup(
                jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogChooseRegionLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabelCountRegion)
                                .addGap(72, 72, 72)
                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelTundra)
                                        .addComponent(jLabelMixedForest)
                                        .addComponent(jLabelDesert))
                                .addGap(18, 18, 18)
                                .addGroup(jDialogChooseRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxTundra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxMixedForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxDesert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(jButtonChooseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
        );

        jTableCurrentRegion.setBorder(new javax.swing.border.MatteBorder(null));
        jTableCurrentRegion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableCurrentRegion.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
        ));
        jTableCurrentRegion.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableCurrentRegion.getTableHeader().setReorderingAllowed(false);
        jScrollPaneRegions.setViewportView(jTableCurrentRegion);

        jButtonCutTree.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCutTree.setText("Срубить дерево");
        jButtonCutTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCutTreeActionPerformed(evt);
            }
        });

        jButtonBuildHouse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuildHouse.setText("Построить дом");
        jButtonBuildHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildHouseActionPerformed(evt);
            }
        });

        jButtonBuildFire.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuildFire.setText("Разжечь костер");
        jButtonBuildFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildFireActionPerformed(evt);
            }
        });

        jButtonExitGame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExitGame.setText("Выйти");
        jButtonExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitGameActionPerformed(evt);
            }
        });

        jButtonBuildWell.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuildWell.setText("Построить колодец");
        jButtonBuildWell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildWellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGameTableLayout = new javax.swing.GroupLayout(jPanelGameTable);
        jPanelGameTable.setLayout(jPanelGameTableLayout);
        jPanelGameTableLayout.setHorizontalGroup(
                jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGameTableLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPaneRegions)
                                        .addGroup(jPanelGameTableLayout.createSequentialGroup()
                                                .addComponent(jButtonCutTree)
                                                .addGap(39, 39, 39)
                                                .addComponent(jButtonBuildHouse)
                                                .addGap(49, 49, 49)
                                                .addComponent(jButtonBuildFire)
                                                .addGap(42, 42, 42)
                                                .addComponent(jButtonBuildWell)
                                                .addGap(307, 307, 307)
                                                .addComponent(jButtonExitGame)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanelGameTableLayout.setVerticalGroup(
                jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGameTableLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPaneRegions, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addGroup(jPanelGameTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonCutTree, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBuildHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBuildFire, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonExitGame, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBuildWell, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonMap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMap.setText("Карта");
        jButtonMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapActionPerformed(evt);
            }
        });

        jLabelCurrentRegion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPanelGameTopLayout = new javax.swing.GroupLayout(jPanelGameTop);
        jPanelGameTop.setLayout(jPanelGameTopLayout);
        jPanelGameTopLayout.setHorizontalGroup(
                jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGameTopLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCurrentRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(290, 290, 290)
                                .addComponent(jButtonMap)
                                .addGap(38, 38, 38))
        );
        jPanelGameTopLayout.setVerticalGroup(
                jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGameTopLayout.createSequentialGroup()
                                .addGroup(jPanelGameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanelGameTopLayout.createSequentialGroup()
                                                .addContainerGap(44, Short.MAX_VALUE)
                                                .addComponent(jLabelCurrentRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelGameTopLayout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(jButtonMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanelGameImageLayout = new javax.swing.GroupLayout(jPanelGameImage);
        jPanelGameImage.setLayout(jPanelGameImageLayout);
        jPanelGameImageLayout.setHorizontalGroup(
                jPanelGameImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelGameImageLayout.setVerticalGroup(
                jPanelGameImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrameGameLayout = new javax.swing.GroupLayout(jFrameGame.getContentPane());
        jFrameGame.getContentPane().setLayout(jFrameGameLayout);
        jFrameGameLayout.setHorizontalGroup(
                jFrameGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelGameTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelGameTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jFrameGameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelGameImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jFrameGameLayout.setVerticalGroup(
                jFrameGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameGameLayout.createSequentialGroup()
                                .addComponent(jPanelGameTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelGameImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelGameTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelMap.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelMap.setText("Карта мира");

        jListMap.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneMap.setViewportView(jListMap);

        jButtonChooseCurrentRegion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonChooseCurrentRegion.setText("Перейти");
        jButtonChooseCurrentRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseCurrentRegionActionPerformed(evt);
            }
        });

        jButtonCloseMap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCloseMap.setText("Закрыть");
        jButtonCloseMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogMapLayout = new javax.swing.GroupLayout(jDialogMap.getContentPane());
        jDialogMap.getContentPane().setLayout(jDialogMapLayout);
        jDialogMapLayout.setHorizontalGroup(
                jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                .addGroup(jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                                .addGap(253, 253, 253)
                                                .addComponent(jLabelMap))
                                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addGroup(jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPaneMap, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelImageMap, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jButtonChooseCurrentRegion)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButtonCloseMap)
                                                                .addGap(11, 11, 11)))))
                                .addGap(60, 78, Short.MAX_VALUE))
        );
        jDialogMapLayout.setVerticalGroup(
                jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogMapLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMap)
                                .addGap(28, 28, 28)
                                .addComponent(jLabelImageMap, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneMap, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDialogMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonChooseCurrentRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCloseMap, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelGame.setText("Game");

        jButtonStartGame.setText("Начать");
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStartGameLayout = new javax.swing.GroupLayout(jPanelStartGame);
        jPanelStartGame.setLayout(jPanelStartGameLayout);
        jPanelStartGameLayout.setHorizontalGroup(
                jPanelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStartGameLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(258, 258, 258))
                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                .addGroup(jPanelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(jLabelImageGame, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                                .addGap(277, 277, 277)
                                                .addComponent(jLabelGame)))
                                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanelStartGameLayout.setVerticalGroup(
                jPanelStartGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStartGameLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabelGame)
                                .addGap(61, 61, 61)
                                .addComponent(jLabelImageGame, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelStartGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartGameActionPerformed
        jDialogChooseRegion.setVisible(true);
        jDialogChooseRegion.setBounds(0, 100, 645, 399);
    }//GEN-LAST:event_jButtonStartGameActionPerformed

    private void jButtonChooseRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseRegionActionPerformed

        try {
                takeCountRegions();
                cleanComboBox();

                textEditorGameWorld.updateCurrentRegion(gameWorld.getCurrentRegion());
                jDialogChooseRegion.dispose();
                jFrameGame.setVisible(rootPaneCheckingEnabled);
                jFrameGame.setSize(1160, 720);

        } catch (Exception e) {
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonChooseRegionActionPerformed

    private void cleanComboBox() {
        jComboBoxTundra.setSelectedIndex(0);
        jComboBoxMixedForest.setSelectedIndex(0);
        jComboBoxDesert.setSelectedIndex(0);
    }

    private void takeCountRegions() throws Exception {

        int countTundra = jComboBoxTundra.getSelectedIndex();
        int countMixedForest = jComboBoxMixedForest.getSelectedIndex();
        int countDesert = jComboBoxDesert.getSelectedIndex();

        gameWorld.createWorld(countTundra,countMixedForest,countDesert);
    }

    private void jButtonCutTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCutTreeActionPerformed
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.cutTree(chooseObject);
            textEditorGameWorld.updateCurrentRegion();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonCutTreeActionPerformed

    private void jButtonBuildHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuildHouseActionPerformed
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.buildHouse(chooseObject);
            textEditorGameWorld.updateCurrentRegion();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuildHouseActionPerformed

    private void jButtonBuildFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuildFireActionPerformed
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.buildFire(chooseObject);
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }finally {
            textEditorGameWorld.updateCurrentRegion();
        }
    }//GEN-LAST:event_jButtonBuildFireActionPerformed
    private void jButtonBuildWellActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            int chooseObject = jTableCurrentRegion.getSelectedRow();
            gameWorld.buildWell(chooseObject);
            textEditorGameWorld.updateCurrentRegion();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void jButtonExitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitGameActionPerformed
        jFrameGame.dispose();
        gameWorld = new GameWorld();
        textEditorGameWorld.clean();
    }//GEN-LAST:event_jButtonExitGameActionPerformed

    private void jButtonMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapActionPerformed
        jDialogMap.setVisible(true);
        jDialogMap.setBounds(100, 100, 655, 560);
        textEditorMap.setModelMap(gameWorld.getRegions(), gameWorld.getCurrentRegion());
    }//GEN-LAST:event_jButtonMapActionPerformed

    private void jButtonChooseCurrentRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseCurrentRegionActionPerformed
        try{
            int chooseObject = jListMap.getSelectedIndex();
            gameWorld.changeCurrentRegion(chooseObject);
            textEditorGameWorld.updateCurrentRegion(gameWorld.getCurrentRegion());
            jDialogMap.dispose();
        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonChooseCurrentRegionActionPerformed

    private void jButtonCloseMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseMapActionPerformed
        jDialogMap.dispose();
    }//GEN-LAST:event_jButtonCloseMapActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuildFire;
    private javax.swing.JButton jButtonBuildHouse;
    private javax.swing.JButton jButtonBuildWell;
    private javax.swing.JButton jButtonChooseCurrentRegion;
    private javax.swing.JButton jButtonChooseRegion;
    private javax.swing.JButton jButtonCloseMap;
    private javax.swing.JButton jButtonCutTree;
    private javax.swing.JButton jButtonExitGame;
    private javax.swing.JButton jButtonMap;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JComboBox<String> jComboBoxDesert;
    private javax.swing.JComboBox<String> jComboBoxMixedForest;
    private javax.swing.JComboBox<String> jComboBoxTundra;
    private javax.swing.JDialog jDialogChooseRegion;
    private javax.swing.JDialog jDialogMap;
    private javax.swing.JFrame jFrameGame;
    private javax.swing.JLabel jLabelCountRegion;
    private javax.swing.JLabel jLabelCurrentRegion;
    private javax.swing.JLabel jLabelDesert;
    private javax.swing.JLabel jLabelGame;
    private javax.swing.JLabel jLabelImageGame;
    private javax.swing.JLabel jLabelImageMap;
    private javax.swing.JLabel jLabelMap;
    private javax.swing.JLabel jLabelMixedForest;
    private javax.swing.JLabel jLabelTundra;
    private javax.swing.JList<String> jListMap;
    private ImagePanel jPanelGameImage;
    private javax.swing.JPanel jPanelGameTable;
    private javax.swing.JPanel jPanelGameTop;
    private javax.swing.JPanel jPanelStartGame;
    private javax.swing.JScrollPane jScrollPaneMap;
    private javax.swing.JScrollPane jScrollPaneRegions;
    private javax.swing.JTable jTableCurrentRegion;
    // End of variables declaration//GEN-END:variables
}
